apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: color-ingress
  namespace: color-app
spec:
  ingressClassName: traefik
  rules:
  - host: colorapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: color-service
            port:
              number: 80
              